"""added run description

Revision ID: 18528b4eff05
Revises: 344dc6adc5f4
Create Date: 2023-12-08 12:45:25.566040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18528b4eff05'
down_revision = '344dc6adc5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runDescription', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('runDescription')

    # ### end Alembic commands ###
